In [ ]:
#Importing NumPy
import numpy as np

In [ ]:
#Indexing, Slicing and accessing elements & vectors from matrices
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
arr[1]

[ 1  2  3  4  5  6  7  8  9 10]


2

In [ ]:
#Get value in a range
arr[1:5]

array([2, 3, 4, 5])

In [ ]:
#Get value in a range
arr[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
#setting a value with index range (broadcasting-changing certain array values 
#by specifying the index range)
arr[0:5]=100
#show
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
#slicing
arr=np.arange(0,11)
#show
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
slice_of_arr=arr[0:6]
#show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#change slice
slice_of_arr[:]=99
#show slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
#indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
#shape bottom row
arr_2d[1,:]

array([20, 25, 30])

In [ ]:
#shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [ ]:
#getting individual element
arr_2d[2,1]

40

In [ ]:
#getting individual element
arr_2d[0,0]

5

In [ ]:
#matrix slicing
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [ ]:
#matrix slicing
arr_2d[1:3,1:3]

array([[25, 30],
       [40, 45]])

In [ ]:
#matrix slicing
arr_2d[1:3,0:2]

array([[20, 25],
       [35, 40]])